schemaVersion: 2.3.0
metadata:
  name: devworkspace-generator
components:
  - name: builder
    container:
      image: quay.io/devfile/universal-developer-image:ubi10-latest
      memoryRequest: 256Mi
      memoryLimit: 3Gi
      cpuRequest: 100m
      cpuLimit: '1'
commands:
  - id: build
    exec:
      label: "1. Build"
      component: builder
      workingDir: ${PROJECTS_ROOT}/devworkspace-generator
      commandLine: yarn && yarn format:fix && yarn build
  - id: test
    exec:
      label: "2. Run tests"
      component: builder
      workingDir: ${PROJECTS_ROOT}/devworkspace-generator
      commandLine: yarn test
  - id: license-check
    exec:
      label: "3. Check licenses"
      component: builder
      workingDir: ${PROJECTS_ROOT}/devworkspace-generator
      commandLine: yarn license:check
  - id: license-generate
    exec:
      label: "4. Generate licenses"
      component: builder
      workingDir: ${PROJECTS_ROOT}/devworkspace-generator
      commandLine: yarn license:generate
  - id: generate-devworkspace
    exec:
      label: "5. Generate DevWorkspace with Template"
      component: builder
      workingDir: ${PROJECTS_ROOT}/devworkspace-generator
      commandLine: |
        DEFAULT_DEVFILE_URL="https://github.com/che-incubator/quarkus-api-example/tree/main"
        DEFAULT_EDITOR_URL="https://raw.githubusercontent.com/eclipse-che/che-operator/refs/heads/main/editors-definitions/che-code-insiders.yaml"
        echo "Enter devfile URL (default: ${DEFAULT_DEVFILE_URL}):"
        read DEVFILE_URL
        DEVFILE_URL="${DEVFILE_URL:-${DEFAULT_DEVFILE_URL}}"
        echo "Enter editor URL (default: ${DEFAULT_EDITOR_URL}):"
        read EDITOR_URL
        EDITOR_URL="${EDITOR_URL:-${DEFAULT_EDITOR_URL}}"
        node lib/entrypoint.js \
        --devfile-url:"${DEVFILE_URL}" \
        --editor-url:"${EDITOR_URL}" \
        --output-file:/tmp/devworkspace-che-code-latest.yaml \
        --injectDefaultComponent:true \
        --defaultComponentImage:registry.access.redhat.com/ubi8/openjdk-11:latest
